### ISSUE TITLE
Error: Input must be string

### ISSUE THREAD

**Issue by natalia-fernandes** [roberto-slopez/npm-build-zip#2]
**Problem description**

Run the script:
`npm-build-script`

Output:
```
Error: Input must be string
    at sanitize ([...]/node_modules/sanitize-filename/index.js:41:11)
    at module.exports ([...]/node_modules/sanitize-filename/index.js:54:16)
    at [...]/node_modules/npm-build-zip/index.js:31:16
```

Problem: (index.js:31:16)
```
`${sanitize(process.env.npm_package_name)}_${sanitize(process.env.npm_package_version)}${name}.zip`,
```
It seems those env vars cannot be found.

Even though my package.json contains the proper fields:
```
{
  "name": "package-name",
  "version": "0.1.0",
  [...]
}
```
Any insight?

**Comment by natalia-fernandes** [comment]
Node v12.16.3
Mac OS X v10.15.4

**Comment by gilmorem560** [comment]
PR #7 should address this, assuming the intended behavior is to take the package name and version of the package this is executing **on** rather than the npm-build-zip package itself.
